[package]
name = "common"
version = "0.1.0"
authors = ["Marc-André Lureau <marcandre.lureau@redhat.com>"]
edition = "2018"

[dependencies]
libc = "^0.2.76"

[target."cfg(unix)".dependencies]
nix = "^0.18.0"
